update

diff --git a/backend/Jenkinsfile b/backend/Jenkinsfile
--- a/backend/Jenkinsfile
+++ b/backend/Jenkinsfile
@@ -1,31 +1,47 @@
 pipeline {
     agent any
     stages {
-        stage('Build') {
+        stage('Checkout') {
             steps {
-                dir('/workspace') {
-                    sh 'docker build -t utecare-backend:latest .'
+                git url: 'https://github.com/dgeniust/hcmute-care.git', branch: 'deploy/set-up-jenkins-v1'
+            }
+        }
+        stage('Build Docker Image') {
+            steps {
+                dir('backend') { 
+                    script {
+                        sh 'docker build -t utecare-backend:latest .'
+                    }
                 }
             }
         }
         stage('Deploy') {
             steps {
-                dir('/workspace') {
-                    sh 'docker compose down'
-                    sh 'docker compose up -d backend-service'
+                dir('backend') { 
+                    script {
+                        sh 'docker compose down backend-service'
+                        sh 'docker compose up -d  backend-service'
+                    }
                 }
             }
         }
     }
     post {
         success {
-            sh 'echo "Build và Deploy thành công!"'
+            echo 'Build and deployment successful!'
         }
         failure {
-            sh 'echo "Build hoặc Deploy thất bại!"'
+            dir('backend') {
+                script {
+                    echo 'Build failed, cleaning up resources...'
+                    sh 'docker compose rm -f utecare-backend-service || true'
+                    sh 'docker rmi utecare-backend:latest || true'
+                    sh 'docker image prune -f || true'
+                }
+            }
         }
         always {
-            sh 'echo "Pipeline hoàn tất."'
+            echo 'Pipeline completed.'
         }
     }
 }
